"""Initial Fresh Schema

Revision ID: 55b063c0ad71
Revises: 
Create Date: 2026-04-22 04:03:10.500121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b063c0ad71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_catalog',
    sa.Column('model_number', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model_number')
    )
    op.create_index(op.f('ix_device_catalog_model_number'), 'device_catalog', ['model_number'], unique=False)
    op.create_table('labor_rate_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('fee_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_name')
    )
    op.create_index(op.f('ix_labor_rate_config_id'), 'labor_rate_config', ['id'], unique=False)
    op.create_table('parts_inventory',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('part_name', sa.String(), nullable=False),
    sa.Column('current_stock_qty', sa.Integer(), nullable=True),
    sa.Column('moving_average_cost', sa.Float(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_parts_inventory_sku'), 'parts_inventory', ['sku'], unique=False)
    op.create_table('phone_models',
    sa.Column('model_number', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('model_number')
    )
    op.create_index(op.f('ix_phone_models_model_number'), 'phone_models', ['model_number'], unique=False)
    op.create_table('store_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_locations_id'), 'store_locations', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('transfer_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.Enum('Restock', 'Repair_Routing', name='transfertype'), nullable=False),
    sa.Column('destination_location_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_orders_id'), 'transfer_orders', ['id'], unique=False)
    op.create_table('unified_customers',
    sa.Column('crm_id', sa.String(), nullable=False),
    sa.Column('customer_type', sa.Enum('Retail', 'Wholesale', name='customertype'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('shipping_address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tax_exempt_id', sa.String(), nullable=True),
    sa.Column('tax_exempt_expiry', sa.DateTime(), nullable=True),
    sa.Column('pricing_tier', sa.Float(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('crm_id')
    )
    op.create_index(op.f('ix_unified_customers_crm_id'), 'unified_customers', ['crm_id'], unique=False)
    op.create_table('customer_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_authorized_buyer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['unified_customers.crm_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_contacts_id'), 'customer_contacts', ['id'], unique=False)
    op.create_table('customer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['unified_customers.crm_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_documents_id'), 'customer_documents', ['id'], unique=False)
    op.create_table('inventory_audits',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('conducted_by_employee_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_expected', sa.Integer(), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('total_missing', sa.Integer(), nullable=True),
    sa.Column('total_unexpected', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_locations.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_inventory_audits_audit_id'), 'inventory_audits', ['audit_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_percent', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('fulfillment_method', sa.String(), nullable=True),
    sa.Column('shipping_address', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Unpaid', 'Partially_Paid', 'Paid', 'Overdue', name='invoicestatus'), nullable=True),
    sa.Column('is_estimate', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['unified_customers.crm_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('part_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('is_priced', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['parts_inventory.sku'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_intakes_id'), 'part_intakes', ['id'], unique=False)
    op.create_table('repair_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_model_number', sa.String(), nullable=False),
    sa.Column('repair_category', sa.String(), nullable=False),
    sa.Column('default_part_sku', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['default_part_sku'], ['parts_inventory.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_mapping_id'), 'repair_mapping', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'store_a', 'store_b', 'store_c', 'technician', name='roleenum'), nullable=True),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('device_inventory',
    sa.Column('imei', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('sub_location_bin', sa.String(), nullable=True),
    sa.Column('device_status', sa.Enum('Sellable', 'In_QC', 'In_Repair', 'In_Transit', 'Sold', 'Transit_to_Repair', 'Transit_to_Main_Bin', 'Transit_to_QC', name='devicestatus'), nullable=True),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('assigned_transfer_order_id', sa.String(), nullable=True),
    sa.Column('assigned_technician_id', sa.String(), nullable=True),
    sa.Column('sold_to_crm_id', sa.String(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('warranty_expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['users.email'], ),
    sa.ForeignKeyConstraint(['assigned_transfer_order_id'], ['transfer_orders.id'], ),
    sa.ForeignKeyConstraint(['model_number'], ['phone_models.model_number'], ),
    sa.ForeignKeyConstraint(['sold_to_crm_id'], ['unified_customers.crm_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_locations.id'], ),
    sa.PrimaryKeyConstraint('imei')
    )
    op.create_index(op.f('ix_device_inventory_imei'), 'device_inventory', ['imei'], unique=False)
    op.create_index(op.f('ix_device_inventory_location_id'), 'device_inventory', ['location_id'], unique=False)
    op.create_table('inventory_audit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('variance_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['inventory_audits.audit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_audit_items_id'), 'inventory_audit_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_audit_items_imei'), 'inventory_audit_items', ['imei'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_id'), 'payment_records', ['id'], unique=False)
    op.create_table('device_cost_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(), nullable=False),
    sa.Column('cost_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imei'], ['device_inventory.imei'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_cost_ledger_id'), 'device_cost_ledger', ['id'], unique=False)
    op.create_table('device_history_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['imei'], ['device_inventory.imei'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_device_history_log_log_id'), 'device_history_log', ['log_id'], unique=False)
    op.create_table('repair_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(), nullable=False),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Pending_Triage', 'In_Repair', 'Completed', 'Cancelled', name='repairstatus'), nullable=True),
    sa.Column('assigned_tech_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_tech_id'], ['users.email'], ),
    sa.ForeignKeyConstraint(['imei'], ['device_inventory.imei'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_tickets_id'), 'repair_tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_tickets_id'), table_name='repair_tickets')
    op.drop_table('repair_tickets')
    op.drop_index(op.f('ix_device_history_log_log_id'), table_name='device_history_log')
    op.drop_table('device_history_log')
    op.drop_index(op.f('ix_device_cost_ledger_id'), table_name='device_cost_ledger')
    op.drop_table('device_cost_ledger')
    op.drop_index(op.f('ix_payment_records_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_inventory_audit_items_imei'), table_name='inventory_audit_items')
    op.drop_index(op.f('ix_inventory_audit_items_id'), table_name='inventory_audit_items')
    op.drop_table('inventory_audit_items')
    op.drop_index(op.f('ix_device_inventory_location_id'), table_name='device_inventory')
    op.drop_index(op.f('ix_device_inventory_imei'), table_name='device_inventory')
    op.drop_table('device_inventory')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repair_mapping_id'), table_name='repair_mapping')
    op.drop_table('repair_mapping')
    op.drop_index(op.f('ix_part_intakes_id'), table_name='part_intakes')
    op.drop_table('part_intakes')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_audits_audit_id'), table_name='inventory_audits')
    op.drop_table('inventory_audits')
    op.drop_index(op.f('ix_customer_documents_id'), table_name='customer_documents')
    op.drop_table('customer_documents')
    op.drop_index(op.f('ix_customer_contacts_id'), table_name='customer_contacts')
    op.drop_table('customer_contacts')
    op.drop_index(op.f('ix_unified_customers_crm_id'), table_name='unified_customers')
    op.drop_table('unified_customers')
    op.drop_index(op.f('ix_transfer_orders_id'), table_name='transfer_orders')
    op.drop_table('transfer_orders')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_store_locations_id'), table_name='store_locations')
    op.drop_table('store_locations')
    op.drop_index(op.f('ix_phone_models_model_number'), table_name='phone_models')
    op.drop_table('phone_models')
    op.drop_index(op.f('ix_parts_inventory_sku'), table_name='parts_inventory')
    op.drop_table('parts_inventory')
    op.drop_index(op.f('ix_labor_rate_config_id'), table_name='labor_rate_config')
    op.drop_table('labor_rate_config')
    op.drop_index(op.f('ix_device_catalog_model_number'), table_name='device_catalog')
    op.drop_table('device_catalog')
    # ### end Alembic commands ###
