import React from 'react';

export interface PrintableViewProps {
  manifestId: string;
  origin: string;
  destination: string;
  courierName: string;
  imeis: string[];
}

export const PrintableView: React.FC<PrintableViewProps> = ({
  manifestId,
  origin,
  destination,
  courierName,
  imeis
}) => {
  return (
    <div className="hidden print:block p-8 bg-white text-black min-h-screen">
      <div className="flex justify-between items-center border-b-2 border-black pb-4 mb-6">
        <div>
          <h1 className="text-3xl font-bold tracking-wider">TRANSFER MANIFEST</h1>
          <p className="text-sm text-gray-600 mt-1">Date: {new Date().toLocaleDateString()}</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-semibold uppercase tracking-widest text-gray-500 mb-1">Manifest ID</p>
          <p className="text-4xl font-mono font-bold">{manifestId}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div className="p-4 border border-gray-300 rounded">
          <p className="text-xs uppercase text-gray-500 font-bold mb-1">Origin</p>
          <p className="text-lg font-semibold">{origin}</p>
        </div>
        <div className="p-4 border border-gray-300 rounded">
          <p className="text-xs uppercase text-gray-500 font-bold mb-1">Destination</p>
          <p className="text-lg font-semibold">{destination}</p>
        </div>
      </div>

      <div className="mb-8">
        <h2 className="text-lg font-bold mb-3 border-b border-gray-300 pb-2">Items ({imeis.length})</h2>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr>
              <th className="border-b-2 border-gray-400 py-2 w-16">#</th>
              <th className="border-b-2 border-gray-400 py-2">IMEI</th>
            </tr>
          </thead>
          <tbody>
            {imeis.map((imei, index) => (
              <tr key={index} className="border-b border-gray-200">
                <td className="py-2 text-gray-600">{index + 1}</td>
                <td className="py-2 font-mono">{imei}</td>
              </tr>
            ))}
            {imeis.length === 0 && (
              <tr>
                <td colSpan={2} className="py-4 text-center text-gray-500 italic">No items scanned.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <div className="mt-16 pt-8 border-t-2 border-black grid grid-cols-2 gap-12">
        <div>
          <p className="text-sm font-semibold mb-8 uppercase text-gray-600">Dispatched By (Signature)</p>
          <div className="border-b border-black w-full"></div>
        </div>
        <div>
          <p className="text-sm font-semibold mb-8 uppercase text-gray-600">Courier / Received By (Signature)</p>
          <div className="border-b border-black w-full"></div>
          <p className="text-sm mt-2">Name: <span className="font-semibold">{courierName || '__________________'}</span></p>
        </div>
      </div>
      
      <div className="mt-8 text-center text-xs text-gray-400">
        Generated by System • Keep this document for your records
      </div>
    </div>
  );
};
